import {expect,it,vi} from 'vitest';
import {CdpTaskPages,CdpTaskConfigSchema,type CdpTarget} from './cdp-task-pages.js';
import {BrowserError} from './browser.js';
const config={endpoint:'http://127.0.0.1:9222/',instanceId:'browser-1',pauseFile:'/private/dtc-paused'};
const signal=()=>AbortSignal.timeout(5000);
class Memory{data=new Map<string,Uint8Array>();async read(k:string){return this.data.get(k)??null;}async create(k:string,v:Uint8Array){if(this.data.has(k))return 'exists' as const;this.data.set(k,v);return 'created' as const;}}
function fixture(){const journal=new Memory(),tabs:CdpTarget[]=[{id:'user',type:'page',url:'https://example.com'}];
 const port={guard:vi.fn(async(s:AbortSignal)=>{s.throwIfAborted();}),list:vi.fn(async()=>tabs.slice()),create:vi.fn(async(marker:string)=>{tabs.push({id:'owned',type:'page',url:marker});return 'owned';}),close:vi.fn(async(id:string)=>{tabs.splice(tabs.findIndex(t=>t.id===id),1);}),call:vi.fn()};return{journal,tabs,port,pages:new CdpTaskPages(config,journal,port)};}
it('success closes exact page and popup descendants, preserves unrelated user pages',async()=>{const f=fixture();expect(await f.pages.using('task',signal(),async()=>{f.tabs.push({id:'popup',type:'page',url:'https://brand.example',openerId:'owned'},{id:'nested',type:'page',url:'https://brand.example',openerId:'popup'});return 'saved';})).toBe('saved');expect(f.tabs.map(t=>t.id)).toEqual(['user']);expect(f.port.close).toHaveBeenCalledTimes(3);});
it.each(['failure','cancellation'])('%s still uses a fresh cleanup signal',async mode=>{const f=fixture(),c=new AbortController();await expect(f.pages.using('task',c.signal,async()=>{if(mode==='cancellation')c.abort();throw Error(mode);})).rejects.toThrow(mode);expect(f.tabs.map(t=>t.id)).toEqual(['user']);});
it.each([Error,BrowserError])('user-control hard stop does not attempt cleanup (%s)',async E=>{const f=fixture();await expect(f.pages.using('task',signal(),async()=>{throw new E('SOURCE.BROWSER_USER_CONTROL');})).rejects.toThrow('USER_CONTROL');expect(f.port.close).not.toHaveBeenCalled();});
it('lost open acknowledgement recovers exact marker, never creates twice',async()=>{const f=fixture();f.port.create.mockImplementation(async marker=>{f.tabs.push({id:'owned',type:'page',url:marker});throw Error('lost');});await expect(f.pages.open('task',signal())).rejects.toThrow('lost');await expect(f.pages.open('task',signal())).rejects.toThrow('PAGE_OPEN_UNKNOWN');expect(await f.pages.close('task',signal())).toMatchObject({status:'closed'});expect(f.port.create).toHaveBeenCalledOnce();expect(f.tabs.map(t=>t.id)).toEqual(['user']);});
it('cold worker reads persistent ownership and verifies absence again',async()=>{const f=fixture();await f.pages.open('task',signal());const cold=new CdpTaskPages(config,f.journal,f.port);await cold.close('task',signal());await cold.close('task',signal());expect(f.port.close).toHaveBeenCalledOnce();await expect(cold.open('task',signal())).rejects.toThrow('ALREADY_CLOSED');});
it('close acknowledgement lag triggers read-only checks, not repeated close',async()=>{const f=fixture();await f.pages.open('task',signal());let closed=false,n=0;f.port.close.mockImplementation(async()=>{closed=true;});f.port.list.mockImplementation(async()=>{if(closed&&++n===3)f.tabs.splice(1);return f.tabs.slice();});await f.pages.close('task',signal());expect(f.port.close).toHaveBeenCalledOnce();expect(n).toBe(3);});
it('failed close remains pending, no false closed record',async()=>{const f=fixture();f.port.close.mockRejectedValue(Error('unavailable'));await expect(f.pages.using('task',signal(),async()=>1)).rejects.toThrow('CLEANUP_PENDING');expect([...f.journal.data.keys()].some(k=>k.endsWith('/closed.json'))).toBe(false);});
it('pause or browser identity change prevents all close mutations',async()=>{const f=fixture();await f.pages.open('task',signal());f.port.guard.mockRejectedValue(Error('SOURCE.BROWSER_INSTANCE_CHANGED'));await expect(f.pages.close('task',signal())).rejects.toThrow('INSTANCE_CHANGED');expect(f.port.close).not.toHaveBeenCalled();});
it('ambiguous marker cannot be recovered by domain or by closing all tabs',async()=>{const f=fixture();f.port.create.mockImplementation(async marker=>{f.tabs.push({id:'a',type:'page',url:marker},{id:'b',type:'page',url:marker});throw Error('lost');});await expect(f.pages.open('task',signal())).rejects.toThrow();await expect(f.pages.close('task',signal())).rejects.toThrow('OPEN_UNKNOWN');expect(f.port.close).not.toHaveBeenCalled();});
it.each(['http://192.168.0.6:9222/','https://127.0.0.1:9222/','http://user:pass@127.0.0.1:9222/','http://127.0.0.1:9222/path'])('rejects endpoint %s',endpoint=>{expect(CdpTaskConfigSchema.safeParse({...config,endpoint}).success).toBe(false);});

it('does not blindly reclose popup descendants that already vanished',async()=>{const f=fixture();await f.pages.open('task',signal());f.tabs.push({id:'popup-a',type:'page',url:'https://brand.example',openerId:'owned'},{id:'popup-b',type:'page',url:'https://brand.example',openerId:'popup-a'});f.port.close.mockImplementation(async id=>{if(id==='popup-a')f.tabs.splice(2);else f.tabs.splice(f.tabs.findIndex(t=>t.id===id),1);});await f.pages.close('task',signal());expect(f.port.close.mock.calls.map(c=>c[0])).toEqual(['popup-a','owned']);expect(f.tabs.map(t=>t.id)).toEqual(['user']);});
