import {commerceDomExpression} from "./commerce-dom.js";
import{AmazonRenderedProductSchema,AmazonRenderedCatalogSchema}from'@crawl-automation/v3-contracts';
import{EgoBrowserConfigSchema,EgoCliRunner,type EgoBrowserConfig,type EgoCommandRunner}from'@crawl-automation/v3-acquisition';
import{amazonProductAddress,amazonStoreAddress,parseAmazonRenderedProduct,parseAmazonRenderedCatalog}from'./amazon-rendered.js';
export const amazonCatalogExpression=`(()=>{const names=[...document.querySelectorAll('li[class*="Breadcrumbs__breadcrumb__"] a')];const grids=[...document.querySelectorAll('ul[class*="ProductGrid__grid__"]')];if(names.length!==1||!grids.length)throw Error('AMAZON.STORE_TEMPLATE_UNVERIFIED');return {codec:'amazon-catalog-rendered/1',url:location.href,capturedAt:new Date().toISOString(),storeName:names[0].innerText.trim(),deliveryText:document.querySelector('#nav-global-location-popover-link')?.innerText||'',cards:grids.flatMap(g=>[...g.querySelectorAll('li[class*="ProductGridItem__itemOuter__"]')].map(c=>({links:[...c.querySelectorAll('a[href]')].filter(a=>/\\/dp\\//.test(a.href)).map(a=>a.href),title:c.innerText.slice(0,4000),sponsored:/Sponsored|赞助/.test(c.innerText)}))),navigation:[...document.querySelectorAll('nav[class*="Navigation__navBar__"] a[href]')].filter(a=>a.href.includes('/stores/')).map(a=>({label:a.innerText,url:a.href}))}})()`;
export const amazonProductExpression=`(()=>{const ppd=[...document.querySelectorAll('#ppd')],a=ppd[0]?[...ppd[0].querySelectorAll('#ASIN')].map(e=>e.value):[],t=ppd[0]?[...ppd[0].querySelectorAll('#productTitle')]:[];if(ppd.length!==1||!a.length||a.some(v=>!(/^[A-Z0-9]{10}$/.test(v)))||t.length!==1)throw Error('AMAZON.PRODUCT_UNVERIFIED');if(new Set(a).size!==1)throw Error('AMAZON.ASIN_CONFLICT');const brand=ppd[0].querySelector('#bylineInfo');return {codec:'amazon-rendered/1',url:location.href,canonicalUrl:document.querySelector('link[rel="canonical"]')?.href,capturedAt:new Date().toISOString(),asin:a[0],title:t[0].innerText.trim(),commerce:${commerceDomExpression('amazon')},brandRaw:brand?.innerText||'',storeUrl:brand?.href,deliveryText:document.querySelector('#nav-global-location-popover-link')?.innerText||'',sections:['feature-bullets','productDescription','important-information'].map(id=>({id,text:document.getElementById(id)?.innerText||''})).filter(s=>s.text.trim()),variantControls:document.querySelectorAll('#twister,[id^="variation_"],[id^="inline-twister-row-"]').length,variants:[...document.querySelectorAll('#twister a[href],[id^="variation_"] a[href]')].filter(a=>/\\/dp\\/[A-Z0-9]{10}/.test(a.href)).map(a=>({asin:a.href.match(/\\/dp\\/([A-Z0-9]{10})/)[1],url:a.href,label:a.innerText}))}})()`;
/** Actual modal image selections, not thumbnails or script-owned colorImages data.
 * Caller owns the page and keeps it through the bounded file phase, then closes it. */
export class AmazonEgoReader{
 readonly config:EgoBrowserConfig;
 constructor(c:EgoBrowserConfig,private runner:EgoCommandRunner=new EgoCliRunner()){this.config=EgoBrowserConfigSchema.parse(c);if(c.sdk!=='1')throw Error('AMAZON.BROWSER_SDK_UNVERIFIED');}
 private select(){const c=this.config;return`await useOrCreateTaskSpace(${c.taskSpaceId});const tabs=await listTabs();const own=tabs.filter(t=>t.targetId===${JSON.stringify(c.targetId)});if(own.length!==1)throw Error('EGO_TARGET_MISMATCH');await switchTab(own[0].targetId);`;}
 async catalog(url:string,brand:string,signal:AbortSignal){amazonStoreAddress(url);const c=this.config;const p=AmazonRenderedCatalogSchema.parse(await this.runner.run(c.cliPath,this.select()+`if(own[0].url!==${JSON.stringify(url)})await gotoAndWait(${JSON.stringify(url)},{timeout:20});let ready=false;for(let n=0;n<50;n++){if(await js(${JSON.stringify(`!!document.querySelector('ul[class*="ProductGrid__grid__"] li')`)})){ready=true;break;}await new Promise(r=>setTimeout(r,200));}if(!ready)throw Error('AMAZON.STORE_TEMPLATE_UNVERIFIED');const snapshot=await js(${JSON.stringify(amazonCatalogExpression)});`,signal));parseAmazonRenderedCatalog(p,url,brand);return p;}
 async product(url:string,signal:AbortSignal,retain?: (raw:unknown)=>Promise<void>,postalCode?:string){const address=amazonProductAddress(url),c=this.config;
 if(postalCode!==undefined&&!/^\d{5}$/.test(postalCode))throw Error('AMAZON.DELIVERY_POLICY_INVALID');
 const click=`async function click(selector){const pos=await js('(()=>{const list=[...document.querySelectorAll('+JSON.stringify(selector)+')];if(list.length!==1)throw Error("AMAZON.TARGET_AMBIGUOUS");const e=list[0];e.scrollIntoView({block:"center"});const r=e.getBoundingClientRect();if(!r.width||!r.height)throw Error("AMAZON.TARGET_HIDDEN");return {x:r.x+r.width/2,y:r.y+r.height/2}})()');await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',...pos});await cdp('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...pos});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...pos});}`;
 const script=this.select()+`if(own[0].url!==${JSON.stringify(url)})await gotoAndWait(${JSON.stringify(url)},{timeout:20});let ready=false;for(let n=0;n<50;n++){if(await js('document.querySelector("#landingImage")?.complete&&!!document.querySelector("#ASIN")')){ready=true;break;}await new Promise(r=>setTimeout(r,200));}if(!ready)throw Error('AMAZON.PRODUCT_UNVERIFIED');const p=await js(${JSON.stringify(amazonProductExpression)});if(p.asin!==${JSON.stringify(address.asin)})throw Error('AMAZON.ASIN_CONFLICT');${postalCode?`if(!new RegExp('(^|[^0-9])'+${JSON.stringify(postalCode)}+'([^0-9]|$)').test(p.deliveryText))throw Error('AMAZON.DELIVERY_CONTEXT_CONFLICT');`:''}${click}await click('#landingImage');let count=0;for(let n=0;n<50;n++){count=await js('document.querySelectorAll("#ivThumbs .ivThumb[id^=ivImage_]").length');if(count)break;await new Promise(r=>setTimeout(r,200));}if(!count||count>100)throw Error('AMAZON.GALLERY_UNVERIFIED');const gallery=[];let previousThumb=null;for(let i=0;i<count;i++){await click('#ivImage_'+i);let image=null;for(let n=0;n<50;n++){image=await js('(()=>{const selected=document.querySelector("#ivImage_${'\'+i+\''}");const img=document.querySelector("#ivLargeImage img");if(!selected?.classList.contains("selected")||!img?.complete||img.naturalWidth<100||!(img.currentSrc||img.src).startsWith("https://m.media-amazon.com/images/I/"))return null;return {url:img.currentSrc||img.src,alt:img.alt||"",thumbnail:selected.querySelector(".ivThumbImage")?.style.backgroundImage||null}})()');if(image&&(i===0||image.url!==gallery[i-1].url||image.thumbnail&&image.thumbnail===previousThumb))break;image=null;await new Promise(r=>setTimeout(r,200));}if(!image)throw Error('AMAZON.GALLERY_UNVERIFIED');previousThumb=image.thumbnail;gallery.push({index:i,url:image.url,alt:image.alt});}const identity=await js(${JSON.stringify(amazonProductExpression)});if(identity.asin!==p.asin||identity.url!==p.url||identity.title!==p.title)throw Error('AMAZON.ASIN_CONFLICT');if(identity.deliveryText!==p.deliveryText)throw Error('AMAZON.DELIVERY_CONTEXT_CONFLICT');const snapshot={...p,galleryCount:count,gallery};`;
 const raw=await this.runner.run(c.cliPath,script,signal);await retain?.(raw);const p=AmazonRenderedProductSchema.parse(raw);parseAmazonRenderedProduct(p,url,{listingId:address.asin,variantId:null});return p;
 }
}
