import{DtcRenderedProductSchema,DtcRenderedCatalogSchema,ChannelProductEvidenceSchema,ChannelCatalogEvidenceSchema,type DtcSitePolicy}from'@crawl-automation/v3-contracts';
import{sha256}from'@crawl-automation/v3-artifacts';
import{permittedUrl}from'@crawl-automation/v3-acquisition';
export function dtcAddress(raw:string){const normalized=new URL(raw);normalized.hash='';const u=permittedUrl(normalized.href,[normalized.origin]);return{url:u.href,listingId:'dtc-'+sha256(Buffer.from(u.href))};}
export function validateDtcSite(p:DtcSitePolicy){const origin=new URL(p.origin);if(origin.origin!==p.origin||origin.protocol!=='https:'||p.catalogPages.some(u=>new URL(u).origin!==p.origin))throw Error('DTC.SITE_POLICY_INVALID');for(const o of p.imageOrigins)if(new URL(o).origin!==o||new URL(o).protocol!=='https:')throw Error('DTC.SITE_POLICY_INVALID');if(p.selectedUrls?.some(u=>new URL(u).origin!==p.origin||!new URL(u).pathname.startsWith(p.productPathPrefix)))throw Error('DTC.SITE_POLICY_INVALID');}
export function parseDtcRenderedProduct(raw:unknown,expected:string,owner:{listingId:string;variantId:string|null}){const p=DtcRenderedProductSchema.parse(raw),a=dtcAddress(expected);if(p.url!==a.url||p.listingId!==a.listingId||owner.listingId!==a.listingId||owner.variantId!==null)throw Error('DTC.IDENTITY_UNVERIFIED');
 const esc=(s:string)=>'<p>'+s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')+'</p>';
 return ChannelProductEvidenceSchema.parse({codec:'channel-product/1',channel:'dtc',listingId:a.listingId,variantId:null,url:a.url,title:p.title,brandRaw:p.brandName,variantOptions:[],variants:[],detailsHtml:p.legacy?.detailsHtml??(p.sections.map(esc).join('\n')||null),factsCandidates:[],imageCandidates:[...new Set(p.images)].map(url=>({url,variantId:null,basis:'selected-gallery',verifiedOriginal:false})),warnings:['DTC.SELECTED_ONLY','DTC.COVERAGE_UNVERIFIED']});}
export function parseDtcRenderedCatalog(raw:unknown,expected:string,brand:string){const p=DtcRenderedCatalogSchema.parse(raw);if(p.url!==dtcAddress(expected).url||p.brandName!==brand)throw Error('DTC.CATALOG_IDENTITY');for(const e of p.entries)if(e.listingId!==dtcAddress(e.url).listingId)throw Error('DTC.CATALOG_IDENTITY');return ChannelCatalogEvidenceSchema.parse({codec:'channel-catalog/1',channel:'dtc',url:p.url,entries:p.entries,nextUrl:null,completion:'unverified_end',reportedTotal:null,warnings:['DTC.COVERAGE_UNVERIFIED']});}
