// Generates the OCR API types from the API's own OpenAPI document (apps/ocr-service/openapi.json), with binary
// uploads typed as Blob, as the openapi-typescript documentation shows. Run: pnpm generate:ocr-api
import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const source = new URL("../../../apps/ocr-service/openapi.json", import.meta.url);
const target = new URL("../src/ocr/api/ocr-api.generated.ts", import.meta.url);
const blob = ts.factory.createTypeReferenceNode(ts.factory.createIdentifier("Blob"));

const nodes = await openapiTS(JSON.parse(await readFile(source, "utf8")), {
  transform: (schema) => (schema.format === "binary" ? blob : undefined),
});
const banner =
  "// Generated by scripts/generate-ocr-api.ts from apps/ocr-service/openapi.json. Do not edit.\n";
await writeFile(target, banner + astToString(nodes));
