/** Generate private files only; no DB writes, workflow submission or resident replacement. */
import{readFile,writeFile,mkdir,readdir}from'node:fs/promises';import{dirname,join,resolve}from'node:path';import{fileURLToPath}from'node:url';import{hostname}from'node:os';import{z}from'zod';
import{artifactBuildId,parseWorkerConfig,taskQueueFor}from'@crawl-automation/v3-worker-runtime';import{DtcSitePolicySchema,CatalogScopeSchema}from'@crawl-automation/v3-contracts';import{DtcLiveConfigSchema}from'./dtc-live-config.js';import{DtcNodeSchema}from'./dtc-node.js';import{readGncPrivateJson}from'./gnc-config.js';import{validateDtcSite}from'@crawl-automation/v3-channels';
export const DtcPrepareSchema=z.strictObject({target:z.enum(['windows','mini']),root:z.string().min(1),queueScope:z.string().regex(/^dtc-[a-z0-9-]{1,40}$/),baseRuntime:z.string(),baseLive:z.string(),baseLabel:z.string(),scope:CatalogScopeSchema,site:DtcSitePolicySchema,browser:DtcLiveConfigSchema.shape.browser,browserResource:z.string().min(1),browserModelResource:z.string().min(1),codex:DtcLiveConfigSchema.shape.codex,evidencePrefix:z.string().min(1)});
export async function prepareDtc(file:string){const s=DtcPrepareSchema.parse(await readGncPrivateJson(file));if(process.platform!==(s.target==='windows'?'win32':'darwin'))throw Error('DTC.PREPARE_HOST_MISMATCH');validateDtcSite(s.site);if(s.scope.channel!=='dtc'||s.scope.rootUrl!==s.site.catalogPages[0])throw Error('DTC.SOURCE_MISMATCH');
 const root=resolve(s.root),release=dirname(fileURLToPath(import.meta.url));if(!release.startsWith(root+'/')&&!release.startsWith(root+'\\'))throw Error('DTC.RELEASE_MUST_BE_INSIDE_ROOT');
 const dir=join(root,'private'),base=await readGncPrivateJson(s.baseLive) as any,label=await readGncPrivateJson(s.baseLabel) as any,runtime=parseWorkerConfig(await readGncPrivateJson(s.baseRuntime));
 const files=(await readdir(release)).filter(n=>n.endsWith('.js')).sort().map(n=>join(release,n)),build=await artifactBuildId(files),wfBuild=await artifactBuildId([...files,join(release,'product-workflows.cjs')].sort());await mkdir(dir,{recursive:true,mode:0o700});
 const put=async(name:string,v:unknown)=>{const path=join(dir,name),value=JSON.stringify(v,null,2);try{await writeFile(path,value,{flag:'wx',mode:0o600});}catch(e){if((e as NodeJS.ErrnoException).code!=='EEXIST'||await readFile(path,'utf8')!==value)throw Error('DTC.CONFIG_EXISTS_CHANGED');}return path;};
 const jobs:any[]=[],queues:Record<string,string>={},windows:Record<string,string>={};
 async function define(key:string,role:string,entry:string,capability:string,compatibility:string,variable?:string,privatePath?:string,wf=false){const config=parseWorkerConfig({...runtime,role,capability,compatibility,hostId:`${s.target}-${role}`,queueScope:s.queueScope,expectedBuildId:wf?wfBuild:build,concurrency:wf?4:1,shutdownGraceMs:60000,shutdownForceMs:120000,startupTimeoutMs:120000});queues[key]=taskQueueFor(config);const browser=['dtc-capture','dtc-catalog-source','dtc-file'].includes(role);if((s.target==='windows')!==browser)return;
  const path=await put(role+'.runtime.json',config);if(browser)windows[role.slice(4)]=path;else jobs.push({id:role,entry:join(release,entry+'.js'),env:{V3_WORKER_ENABLED:'true',V3_WORKER_CONFIG:path,...(variable?{[variable+'_ENABLED']:'true',[variable+'_CONFIG']:privatePath}:{})}});
 }
 const names:Record<string,string>={plan:'plan',page:'page',pageText:'page-text',imagePrepare:'image-prepare',ocr:'ocr',ocrReceipts:'ocr-receipts',keywords:'keywords',source:'source',manifest:'manifest',text:'text',textReceipts:'text-receipts',vision:'vision',core:'core',assembly:'assembly',collection:'collection',review:'review',resources:'resources'};
 const storage={r2:{...base.r2,prefix:s.evidencePrefix},r2Credentials:base.r2Credentials};
 for(const[key,name]of Object.entries(names)){const privatePath=join(dir,'label-'+name+'.json');if(s.target==='mini'){const c={...label,...storage,root:join(root,'label'),storageId:s.queueScope};if(!['text','vision'].includes(name))delete c.codex;if(name!=='ocr')delete c.ocrProvider;await put('label-'+name+'.json',c);}await define(key,'channel-label-'+name,'channel-label-worker','channel.label.'+name,'channel-label-v1','V3_CHANNEL_LABEL',privatePath);}
 const dtcPrivate=join(dir,'dtc.json');for(const role of['control','catalog-source','catalog-ledger','product-input','capture','file','review'])await define('dtc-'+role,'dtc-'+role,'dtc-live-worker','dtc.'+role,'dtc-live-v1','V3_DTC_LIVE',dtcPrivate);
 const planPrivate=join(dir,'plan.json');if(s.target==='mini')await put('plan.json',{cacheRoot:join(root,'plan-cache'),journalRoot:join(root,'plan-journal'),reviewDatabase:base.database,...storage});await define('productPlan','channel-product-input','channel-plan-worker','channel.product-input','channel-plan-v1','V3_CHANNEL_PLAN',planPrivate);
 for(const[key,role,cap,compat]of[['brandWorkflow','dtc-brand-workflow','dtc.control','dtc-live-v1'],['productWorkflow','dtc-product-workflow','dtc.product-input','dtc-live-v1'],['catalogWorkflow','catalog-workflow','catalog.workflow','catalog-v1'],['labelWorkflow','channel-label-workflow','channel.saved-label','channel-label-v1']])await define(key!,role!,'product-workflow-worker',cap!,compat!,undefined,undefined,true);
 const gate=(activities:unknown,reviewStopCheck=false)=>({queue:queues.resources,activities,maxWaitSeconds:900,reviewStopCheck}),browser=[{resourceId:s.browserResource,units:1}],model=[{resourceId:s.browserModelResource,units:1}];
 const c=DtcLiveConfigSchema.parse({clusterId:base.clusterId,database:base.database,...(base.resourceDatabase?{resourceDatabase:base.resourceDatabase}:{}),...storage,journalRoot:join(root,'source-journal'),pageJournalRoot:join(root,'browser-pages'),cacheRoot:join(root,'source-cache'),browser:s.browser,browserResource:s.browserResource,browserModelResource:s.browserModelResource,egressId:'windows-dtc-host/1',scope:s.scope,brandName:s.site.brandName,site:s.site,...(s.codex?{codex:s.codex}:{}),maxPages:s.site.catalogPages.length,catalogQueue:queues.catalogWorkflow,catalogQueues:{source:queues['dtc-catalog-source'],ledger:queues['dtc-catalog-ledger'],product:queues.productWorkflow},catalogResources:gate({readCatalogPage:[...browser,...model]}),productQueues:{capture:queues['dtc-capture'],plan:queues.productPlan,file:queues['dtc-file'],label:queues.labelWorkflow,review:queues['dtc-review']},productResources:gate({browserSession:browser,captureDtcProduct:model}),sourceText:base.sourceText,ocr:base.ocr,sourceVisionConfigFingerprint:base.sourceVisionConfigFingerprint,labelText:base.labelText,visionConfigFingerprint:base.visionConfigFingerprint,evidencePolicy:base.evidencePolicy,labelQueues:Object.fromEntries(Object.keys(names).filter(k=>k!=='resources').map(k=>[k,queues[k]])),labelResources:{...base.labelResources,queue:queues.resources}});
 if(s.target==='windows'&&!c.codex)throw Error('DTC.WINDOWS_CODEX_REQUIRED');await put('dtc.json',c);
 if(s.target==='windows')await put('node.json',DtcNodeSchema.parse({version:1,platform:'win32',host:hostname(),root,privateConfig:dtcPrivate,runtimes:windows}));else await put('deployment.json',{platform:'darwin',host:hostname(),root,node:process.execPath,jobs,resources:[],database:base.resourceDatabase??base.database});
 await put('routing.json',{queueScope:s.queueScope,scope:s.scope,queues,brandTarget:{taskQueue:queues.brandWorkflow},activityBuild:build,workflowBuild:wfBuild});console.log(JSON.stringify({event:'DTC_CONFIG_PREPARED',target:s.target,roleCount:s.target==='windows'?3:jobs.length,dir,submissionCount:0}));
}
if(process.argv[1]?.endsWith("dtc-prepare.js")){try{if(!process.argv[2])throw Error();await prepareDtc(process.argv[2]);}catch(e){console.error(e instanceof Error&&/^DTC\.[A-Z_]+$/.test(e.message)?e.message:'DTC.PREPARE_FAILED');process.exitCode=1;}}
