/** Explicit terminal-workflow recovery. Never guesses ownership or releases quarantined permits. */
import{readFile,open,unlink}from'node:fs/promises';import{join}from'node:path';import{fileURLToPath}from'node:url';import{Connection,Client}from'@temporalio/client';
import{parseWorkerConfig}from'@crawl-automation/v3-worker-runtime';import{CdpTaskPages,LoopbackCdp}from'@crawl-automation/v3-acquisition';import{createR2Objects,sha256}from'@crawl-automation/v3-artifacts';import{TextLocalStore}from'@crawl-automation/v3-text';import{readGncPrivateJson}from'./gnc-config.js';import{loadDtcNode,pendingDtcPages}from'./dtc-node.js';
export async function recoverDtc(file:string){const{node,config}=await loadDtcNode(file);const lock=join(node.root,'supervisor.lock'),handle=await open(lock,'wx',0o600);await handle.writeFile(JSON.stringify({pid:process.pid,recovery:true}));await handle.close();let safe=false;
 try{for(const role of['capture','file','catalog-source']){let health:any;try{health=JSON.parse(await readFile(join(node.root,role+'.health.json'),'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}if(health?.pid){try{process.kill(health.pid,0);throw Error('DTC.WORKER_STILL_PRESENT');}catch(e){if((e as NodeJS.ErrnoException).code!=='ESRCH')throw e;}}}
 const runtime=parseWorkerConfig(await readGncPrivateJson(node.runtimes.capture)),t=runtime.transport,connection=await Connection.connect({address:runtime.address,connectTimeout:'15 seconds',...(t.mode==='mtls'?{tls:{serverNameOverride:t.serverName,serverRootCACertificate:await readFile(t.caFile),clientCertPair:{crt:await readFile(t.certFile),key:await readFile(t.keyFile)}}}:{})});
 const r2=createR2Objects(config.r2,config.r2Credentials);try{const client=new Client({connection,namespace:runtime.namespace}),local=await TextLocalStore.open(config.pageJournalRoot),pages=new CdpTaskPages(config.browser,local,new LoopbackCdp(config.browser));
 for(const taskId of await pendingDtcPages(config.pageJournalRoot)){const s=AbortSignal.timeout(30000),bytes=await local.read(`v3/dtc-page-executions/${sha256(Buffer.from(taskId))}.json`,65536,s);if(!bytes)throw Error('DTC.RECOVERY_BINDING_MISSING');const b=JSON.parse(Buffer.from(bytes).toString());if(b.taskId!==taskId||b.namespace!==runtime.namespace||JSON.stringify(b.browser)!==JSON.stringify(config.browser))throw Error('DTC.RECOVERY_BINDING_CONFLICT');const run=await client.workflow.getHandle(b.execution.workflowId,b.execution.runId).describe();if(run.runId!==b.execution.runId||!['COMPLETED','FAILED','CANCELED','TERMINATED','TIMED_OUT'].includes(run.status.name))throw Error('DTC.RECOVERY_WORKFLOW_ACTIVE');
 const proof=await pages.close(taskId,s);await r2.store.create(`v3/dtc-page-recovery/${sha256(Buffer.from(taskId))}.json`,Buffer.from(JSON.stringify({binding:b,proof,permits:'quarantined-not-released'})),'application/json',s);console.log(JSON.stringify({event:'DTC_PAGE_RECOVERED',taskId,status:proof.status,permits:'quarantined'}));}
 safe=true;
 }finally{r2.close();await connection.close();}
 }finally{if(safe)await unlink(lock);}
}
if(process.argv[1]?.endsWith("dtc-recover.js")){try{if(!process.argv[2])throw Error();await recoverDtc(process.argv[2]);}catch(e){console.error(e instanceof Error&&/^DTC\.[A-Z_]+$/.test(e.message)?e.message:'DTC.RECOVERY_PENDING_PRESERVE_LOCK');process.exitCode=1;}}
