import assert from'node:assert/strict';import{hostname}from'node:os';import{readFile,writeFile,mkdir}from'node:fs/promises';import pg from'pg';import{Client,Connection}from'@temporalio/client';import{EgoCliRunner}from'@crawl-automation/v3-acquisition';import{createR2Objects}from'@crawl-automation/v3-artifacts';import{PostgresResourceAdmission}from'../../../packages/v3-product/src/resource-admission.js';
async function main(){assert.match(hostname(),/^barrydeMac-mini(?:\.|$)/);assert.equal(process.argv[2],'--verified-catalog-close');const request='0d54ac76-6e53-4af9-8040-4354f60339b4',root='/Users/barry/apps/crawlv3-batch-a.UiA4dx',base=root+'/live/amazon-mainflow-20260911/release-amazon-mainflow-20260911',dir=base+'/catalog-recovery';await mkdir(dir,{mode:0o700});const read=async(p:string)=>JSON.parse(await readFile(p,'utf8')),c=await read(base+'/amazon.private.json'),r=await read(base+'/amazon-brand-workflow.runtime.json'),t=r.transport;assert.equal(new URL(c.database.connectionString).pathname,'/crawler_v3_test');
 const connection=await Connection.connect({address:r.address,tls:{serverNameOverride:t.serverName,serverRootCACertificate:await readFile(t.caFile),clientCertPair:{crt:await readFile(t.certFile),key:await readFile(t.keyFile)}}}),db=new pg.Pool({connectionString:c.database.connectionString}),remote=createR2Objects(c.r2,c.r2Credentials);
 try{const client=new Client({connection,namespace:r.namespace}),id='v3-collection-'+request+'-catalog',h=client.workflow.getHandle(id),d=await h.describe(),history=await h.fetchHistory();assert.equal(d.type,'CatalogWorkflow');assert.equal(d.status.name,'COMPLETED');assert.equal(d.raw.pendingActivities?.length??0,0);assert.deepEqual(await h.result(),{status:'incomplete'});const scheduled=history.events?.filter(e=>e.activityTaskScheduledEventAttributes?.activityType?.name==='readCatalogPage')??[];assert.equal(scheduled.length,1);assert.equal(history.events?.filter(e=>e.childWorkflowExecutionStartedEventAttributes).length,0);
 const audit=await read(root+'/live/amazon-entry-20260911/request-'+request+'/report.json');assert.equal(audit.closures[0].record.pages,0);assert.equal(audit.counts.collected_product,0);assert.equal(audit.counts.processing_result,0);
 const pageRoot=c.pageJournalRoot+'/v3/browser-pages/a6c76ef047b194255e2e35c4e6fe9571a9cc7ec076d7ce5c34adb39a35407c9a',opened=await read(pageRoot+'/opened.json'),closed=await read(pageRoot+'/closed.json');assert.deepEqual(closed,opened);assert.equal(opened.targetId,'9872FEA96A12398BC41F9B49E824FFC7');
 const snapshot=await new EgoCliRunner().run('/Users/barry/.local/bin/ego-browser','await useOrCreateTaskSpace(1);const snapshot={tabs:await listTabs()};',AbortSignal.timeout(10000)) as any;assert.ok(snapshot.tabs.every((x:any)=>x.targetId!==opened.targetId));
 const permits=(await db.query('SELECT permit_id,request,released_at FROM resource_permit WHERE request->>\'workflowId\'=$1',[id])).rows;assert.equal(permits.length,1);const p=permits[0];assert.equal(p.request.runId,d.runId);assert.deepEqual(p.request.needs,[{resourceId:'mini-ego-space-1',units:1}]);assert.equal(p.released_at,null);
 const proof={at:new Date().toISOString(),requestId:request,catalogId:id,runId:d.runId,status:d.status.name,page:closed,targetAbsent:true,permit:p.request,providerCalls:0,productWrites:0,automaticRetry:false};const bytes=Buffer.from(JSON.stringify(proof));const key='v3/amazon-recovery/'+request+'/verified-close.json';assert.equal(await remote.store.create(key,bytes,'application/json',AbortSignal.timeout(30000)),'created');assert.deepEqual(Buffer.from((await remote.store.read(key,65536,AbortSignal.timeout(30000)))!),bytes);await writeFile(dir+'/proof.json',JSON.stringify(proof,null,2));await writeFile(dir+'/history.json',JSON.stringify(history));await new PostgresResourceAdmission(db).release(p.request);const row=(await db.query('SELECT released_at FROM resource_permit WHERE permit_id=$1',[p.permit_id])).rows[0];assert.ok(row.released_at);await writeFile(dir+'/result.json',JSON.stringify({passed:true,at:new Date().toISOString(),releasedPermit:p.permit_id,proofKey:key},null,2));console.log(JSON.stringify({passed:true,releasedPermit:p.permit_id,targetAbsent:true,dir}));
 }finally{remote.close();await db.end();await connection.close();}}
main().catch(e=>{console.error(e instanceof Error?e.message:'RECOVERY_REJECTED');process.exitCode=1;});
