import fs from 'node:fs/promises';import assert from 'node:assert/strict';import pg from 'pg';import {Client,Connection} from '@temporalio/client';import {defaultPayloadConverter} from '@temporalio/common';
import {EgoCliRunner} from '@crawl-automation/v3-acquisition';import {createR2Objects,sha256} from '@crawl-automation/v3-artifacts';import {PostgresResourceAdmission} from '../../../packages/v3-product/src/resource-admission.js';
import {AmazonProductJobSchema} from '@crawl-automation/v3-contracts';
const dir='/Users/barry/apps/crawlv3-history-20260913/amazon-2000-us-20260913',root='/Users/barry/apps/crawlv3-batch-a.UiA4dx',read=async(p:string)=>JSON.parse(await fs.readFile(p,'utf8'));
const mode=process.argv[2];assert.ok(mode==='--audit'||mode==='--release');const m=await read(root+'/live/deployment.json'),c=await read(m.jobs.find((j:any)=>j.id==='amazon-capture').env.V3_AMAZON_LIVE_CONFIG),r=await read(m.jobs.find((j:any)=>j.id==='amazon-brand-workflow').env.V3_WORKER_CONFIG),t=r.transport;
const connection=await Connection.connect({address:r.address,connectTimeout:'15 seconds',tls:{serverNameOverride:t.serverName,serverRootCACertificate:await fs.readFile(t.caFile),clientCertPair:{crt:await fs.readFile(t.certFile),key:await fs.readFile(t.keyFile)}}}),db=new pg.Pool({connectionString:c.database.connectionString,max:1,connectionTimeoutMillis:5000,statement_timeout:5000}),remote=createR2Objects(c.r2,c.r2Credentials);
try{
 const client=new Client({connection,namespace:r.namespace}),batchIds=c.linkBatches.map((b:any)=>b.requestId),permits=(await db.query("select permit_id,request from resource_permit where released_at is null")).rows;
 const browserPermits=permits.filter(p=>p.request.needs.some((n:any)=>n.resourceId===c.browserResource));
 assert.equal(browserPermits.length,1,'exact single held browser permit required');const p=browserPermits[0];assert.deepEqual(p.request.needs,[{units:1,resourceId:'mini-ego-space-1'}]);
 const h=client.workflow.getHandle(p.request.workflowId,p.request.runId),d=await h.describe(),history=await h.fetchHistory();assert.equal(d.runId,p.request.runId);assert.equal(d.type,'AmazonCatalogProductWorkflow');assert.equal(d.status.name,'COMPLETED');assert.equal(d.raw.pendingActivities?.length??0,0);
 assert.equal(history.events?.filter(e=>e.childWorkflowExecutionStartedEventAttributes).length,0);
 const result=await h.result() as any;assert.equal(result.status,'review');
 const rows=(await db.query('select record from review_record where review_id=$1',[result.reviewId])).rows;assert.equal(rows.length,1);const review=rows[0].record;
 assert.equal(result.code,review.failure.code);assert.ok(['amazon.browser','channel.product-input'].includes(review.failure.stage));
 const preparations=history.events?.filter(e=>e.activityTaskScheduledEventAttributes?.activityType?.name==='prepareAmazonProduct')??[];assert.equal(preparations.length,1);
 const prepared=history.events?.find(e=>e.activityTaskCompletedEventAttributes?.scheduledEventId?.toString()===preparations[0]!.eventId?.toString());assert.ok(prepared);
 const job=AmazonProductJobSchema.parse(defaultPayloadConverter.fromPayload(prepared!.activityTaskCompletedEventAttributes!.result!.payloads![0]!));
 assert.equal(job.discovery.workflowId,p.request.workflowId);assert.ok(batchIds.includes(job.discovery.catalogId));
 assert.deepEqual({requestId:review.observation.requestId,brandId:review.observation.brandId,sourceId:review.observation.sourceId,listingId:review.observation.listingId,variantId:review.observation.variantId},
  {requestId:job.discovery.catalogId,brandId:job.discovery.scope.brandId,sourceId:job.discovery.scope.sourceId,listingId:job.discovery.entry.listingId,variantId:job.discovery.entry.variantId});
 const jobBytes=await remote.store.read('v3/amazon-jobs/'+job.discovery.discoveryId+'.json',65536,AbortSignal.timeout(15000));assert.ok(jobBytes);assert.deepEqual(JSON.parse(Buffer.from(jobBytes!).toString()),job);
 const closes=history.events?.filter(e=>e.activityTaskScheduledEventAttributes?.activityType?.name==='closeAmazonProductPage')??[];assert.equal(closes.length,1);const closeEvent=history.events?.find(e=>e.activityTaskCompletedEventAttributes?.scheduledEventId?.toString()===closes[0]!.eventId?.toString());assert.ok(closeEvent);const payloads=closeEvent!.activityTaskCompletedEventAttributes!.result!.payloads!;assert.equal(payloads.length,1);const close:any=defaultPayloadConverter.fromPayload(payloads[0]!);assert.equal(close.status,'closed');assert.equal(close.taskId,job.sessionId);
 const pageRoot=c.pageJournalRoot+'/v3/browser-pages/'+sha256(Buffer.from(JSON.stringify([c.browser,job.sessionId]))),opened=await read(pageRoot+'/opened.json'),closed=await read(pageRoot+'/closed.json');assert.deepEqual(closed,opened);assert.equal(closed.taskId,job.sessionId);assert.equal(closed.targetId,close.targetId);
 const absent=[];for(let i=0;i<3;i++){const snapshot:any=await new EgoCliRunner().run(c.browser.cliPath,'await useOrCreateTaskSpace(1);const snapshot={tabs:await listTabs()};',AbortSignal.timeout(15000));absent.push(snapshot.tabs.every((t:any)=>t.targetId!==closed.targetId));}assert.ok(absent.every(Boolean));
 const proof={codec:'amazon-browser-recovery/1',request:p.request,requestId:job.discovery.catalogId,workflowStatus:d.status.name,reviewId:review.reviewId,taskId:job.sessionId,targetId:closed.targetId,targetsAbsent:absent,closedSha256:sha256(await fs.readFile(pageRoot+'/closed.json')),historySha256:sha256(Buffer.from(JSON.stringify(history)))};
 const out=dir+'/recovery-'+p.permit_id;await fs.mkdir(out,{recursive:true,mode:0o700});await fs.writeFile(out+'/audit.json',JSON.stringify(proof,null,2),{mode:0o600});await fs.writeFile(out+'/history.json',JSON.stringify(history),{mode:0o600});
 if(mode==='--release'){
  const key='v3/amazon-history-recovery/'+p.permit_id+'/proof.json',bytes=Buffer.from(JSON.stringify(proof));await remote.store.create(key,bytes,'application/json',AbortSignal.timeout(30000));assert.deepEqual(Buffer.from((await remote.store.read(key,65536,AbortSignal.timeout(30000)))!),bytes);
  const hb=Buffer.from(JSON.stringify(history));await remote.store.create(key.replace('proof.json','history.json'),hb,'application/json',AbortSignal.timeout(30000));assert.deepEqual(Buffer.from((await remote.store.read(key.replace('proof.json','history.json'),hb.length,AbortSignal.timeout(30000)))!),hb);
  assert.equal((await h.describe()).status.name,'COMPLETED');await new PostgresResourceAdmission(db).release(p.request);assert.ok((await db.query('select released_at from resource_permit where permit_id=$1',[p.permit_id])).rows[0].released_at);
  await fs.writeFile(out+'/released.json',JSON.stringify({at:new Date().toISOString(),proofKey:key,permitId:p.permit_id}),{mode:0o600,flag:'wx'});console.log(JSON.stringify({status:'released',proofKey:key,...proof}));
 }else console.log(JSON.stringify({status:'recoverable',...proof}));
}finally{await db.end();await connection.close();remote.close();}
