import { test } from 'node:test';
import assert from 'node:assert/strict';
import { canonicalWorkflowSourceMap } from './workflow-source-map.js';
const marker='//# sourceMappingURL=data:application/json;charset=utf-8;base64,';
const executable='var __TEMPORAL__ = { value: "do not rewrite workflow code" };\n';
function bundle(root:string,windows=false){
 const sources=[root+'/packages/v3-product/src/workflow.ts',root+'/node_modules/.pnpm/arbitrary-store-layout/node_modules/example/src/index.ts'];
 const map={version:3,file:windows?'workflow-bundle-WIN.js':'workflow-bundle-MAC.js',mappings:'AAAA',names:['value'],sources:windows?sources.map(s=>s.replaceAll('/','\\')):sources,sourcesContent:windows?['export const value=1;\r\n','dependency\r\n']:['export const value=1;\n','dependency\n'],sourceRoot:''};
 return executable+marker+Buffer.from(JSON.stringify(map)).toString('base64')+'\n';
}
test('Mac/Windows checkout paths and source line endings yield the same artifact',()=>{
 const mac=canonicalWorkflowSourceMap(bundle('/Users/build/repo'),'/Users/build/repo');
 const windows=canonicalWorkflowSourceMap(bundle('D:/build/repo',true),'D:\\build\\repo');
 assert.equal(windows,mac);assert.equal(mac.slice(0,mac.indexOf(marker)),executable);
 const map=JSON.parse(Buffer.from(mac.slice(mac.indexOf(marker)+marker.length).trim(),'base64').toString());
 assert.deepEqual(map.sources,['repository/packages/v3-product/src/workflow.ts','dependencies/example/src/index.ts']);
 assert.equal(map.mappings,'AAAA');assert.deepEqual(map.names,['value']);
 assert.equal(canonicalWorkflowSourceMap(mac,'/different/root'),mac);
});
test('unrecognized absolute source paths fail instead of entering a release',()=>{
 assert.throws(()=>canonicalWorkflowSourceMap(bundle('/outside/repo'),'/expected/repo'),/SOURCE_PATH_UNSUPPORTED/);
 assert.throws(()=>canonicalWorkflowSourceMap(executable,'/expected/repo'),/SOURCE_MAP_MISSING/);
});

test('SDK virtual entrypoint source content cannot retain a build-machine path',()=>{
 const make=(root:string)=>{
  const map={version:3,file:'random.js',sources:[root+'/apps/product-autogenerated-entrypoint.cjs'],sourcesContent:['return require('+JSON.stringify(root+'/apps/product.ts')+');'],mappings:'AAAA',names:[]};
  return executable+marker+Buffer.from(JSON.stringify(map)).toString('base64')+'\n';
 };
 const mac=canonicalWorkflowSourceMap(make('/Users/mac/repo'),'/Users/mac/repo');
 assert.equal(canonicalWorkflowSourceMap(make('D:\\work\\repo'),'D:\\work\\repo'),mac);
});
