import { posix } from 'node:path';

const marker = '//# sourceMappingURL=data:application/json;charset=utf-8;base64,';
/** Normalize debugging metadata only. Never rewrite executable Workflow code. */
export function canonicalWorkflowSourceMap(code: string, repositoryRoot: string): string {
  const index = code.lastIndexOf(marker);
  if (index < 0) throw Error('DTC.WORKFLOW_SOURCE_MAP_MISSING');
  const map = JSON.parse(Buffer.from(code.slice(index + marker.length).trim(), 'base64').toString('utf8')) as {version:number;file:string;sourceRoot:string;sources:string[];sourcesContent:(string|null)[]};
  if (map.version !== 3 || !Array.isArray(map.sources) || !Array.isArray(map.sourcesContent) || map.sources.length !== map.sourcesContent.length || map.sources.some(s => typeof s !== 'string') || map.sourcesContent.some(s => s !== null && typeof s !== 'string'))
    throw Error('DTC.WORKFLOW_SOURCE_MAP_INVALID');
  const root = repositoryRoot.replaceAll('\\', '/').replace(/\/$/, '');
  map.sources = map.sources.map(source => {
    const normalized = source.replaceAll('\\', '/');
    const dependency = normalized.lastIndexOf('/node_modules/');
    if (dependency >= 0) return 'dependencies/' + normalized.slice(dependency + '/node_modules/'.length);
    if (normalized.startsWith(root + '/')) return 'repository/' + normalized.slice(root.length + 1);
    // Webpack's own virtual bootstrap sources are already machine-independent.
    if (normalized.startsWith('repository/') || normalized.startsWith('dependencies/') || normalized.startsWith('webpack/')) return posix.normalize(normalized);
    throw Error('DTC.WORKFLOW_SOURCE_PATH_UNSUPPORTED');
  });
  map.sourcesContent = map.sourcesContent.map((source, sourceIndex) => {
    if (source === null) return null;
    const text = source.replaceAll('\r\n', '\n');
    if (!map.sources[sourceIndex]?.endsWith('-autogenerated-entrypoint.cjs')) return text;
    // The SDK's virtual entrypoint embeds an absolute require() path in its
    // source-map source content. Only rewrite that debug copy, never code.
    return text.replace(/"(?:\\.|[^"\\])*"/g, literal => {
      const value = JSON.parse(literal) as string;
      const normalized = value.replaceAll('\\', '/');
      return normalized.startsWith(root + '/') ? JSON.stringify('repository/' + normalized.slice(root.length + 1)) : literal;
    });
  });
  map.file = 'product-workflows.cjs';
  map.sourceRoot = '';
  return code.slice(0, index) + marker + Buffer.from(JSON.stringify(map)).toString('base64') + '\n';
}
